### ISSUE TITLE
Kochia dataset is Unavailable at the link

### ISSUE THREAD

**Issue by sankaraug** [NISL-MSU/HSI-BandSelection#2]
Hi Giorgio,
I want to download Kochia data set mentioned in your paper but is unavailable at the given link.
Can you please do the needful.

Thanks in Advance

**Comment by GiorgioMorales** [comment]
Hello Sankaraug,

Here's the link to the dataset: weed_dataset_w25.hdf5
<https://montanaedu-my.sharepoint.com/:u:/g/personal/w63x712_msu_montana_edu/ETbm2kBq4PlEvLav4SmlsY0BAuqpppyv1PFeFxejC8Ou2w?e=B3sGV7>

Giorgio

**Comment by sankaraug** [comment]
Dear Giorgio,
Thank you for your response
